services:
  frontend-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kle-blog-frontend-app
    ports:
      - "8001:8000"
      - "5173:5173"
    volumes:
      - .:/var/www
    networks:
      - kle-blog-network
    command: php artisan serve --host=0.0.0.0 --port=8000

networks:
  kle-blog-network:
    external: true