services:
  backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kle-blog-backend-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    command: ["sh", "-c", "until [ -f vendor/autoload.php ]; do sleep 1; done; php artisan serve --host=0.0.0.0 --port=8000"]
    networks:
      - kle-blog-network
    depends_on:
      backend-db:
        condition: service_healthy

  backend-db:
    image: mysql:8.0
    container_name: kle-blog-backend-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - kle-blog-db-data:/var/lib/mysql
    networks:
      - kle-blog-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USERNAME}", "-p${DB_PASSWORD}"]
      interval: 3s
      timeout: 3s
      retries: 10

volumes:
  kle-blog-db-data:

networks:
  kle-blog-network:
    name: kle-blog-network
    driver: bridge
