services:
  backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kle-blog-backend-app
    restart: unless-stopped
    tty: true
    ports:
      - "8000:8000"
    
    command: php artisan serve --host=0.0.0.0 --port=8000
    volumes:
      - .:/var/www
    networks:
      - kle-blog-network
    depends_on:
      - backend-mysql

  backend-mysql:
    image: "mysql:8.4"
    container_name: kle-blog-backend-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "kle_blog_backend_db"
    volumes:
      - kle-blog-db-data:/var/lib/mysql
    networks:
      - kle-blog-network

networks:
  kle-blog-network:
    driver: bridge

volumes:
  kle-blog-db-data:
    driver: local